genkernel: working version
I've been using this version of the script to compile my (monolithic) kernel
for the past few releases and everything has gone smoothly (once I figured out
pushd printed the working directory to stdout, corrupting the initramfs... 🤦)

diff --git a/genkernel b/genkernel
--- a/genkernel
+++ b/genkernel
@@ -1,6 +1,5 @@
 #!/bin/bash
 set -euo pipefail
-#set -x
 
 MAKEOPTS="${MAKEOPTS:-$(portageq envvar MAKEOPTS)}"
 NICENESS="${NICENESS:-$(portageq envvar PORTAGE_NICENESS)}"
@@ -31,7 +30,7 @@ clean_src() {
 stderr_tee() {
     while IFS='' read -n 1 -d '' c; do
         printf '%s' "${c}"
-        printf '%s' "${c}" 1>&2
+        printf '%s' "${c}" >&2
     done
 }
 
@@ -65,9 +64,9 @@ set_initramfs_location() {
 }
 
 gen_init_cpio() {
-    pushd usr
+    cd usr
     make gen_init_cpio > /dev/null
-    popd
+    cd ..
 
     FILENAME="$1"; shift
     awk '!x[$2]++' "$FILENAME" | ./usr/gen_init_cpio - "$@"
@@ -80,7 +79,6 @@ build_initramfs() {
 
     cat > "${INIT_LOCATION}" <<'EOF'
 #!/bin/sh
-set -euo pipefail
 
 panic() {
     echo "The kernel will panic as soon as you press Enter."
@@ -88,33 +86,67 @@ panic() {
 }
 trap panic EXIT
 
+mount -t devtmpfs none /dev
+mount -t proc none /proc
+mount -t sysfs none /sys
+
+set -euo pipefail
+
+exec >/dev/console </dev/console 2>&1
+
+cmdline() {
+    local value
+    value=" $(cat /proc/cmdline) "
+    value="${value##* ${1}=}"
+    value="${value%% *}"
+    [ "${value}" != "" ] && echo "${value}"
+}
+
 export PATH=/bin
-mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
-mount -t proc -o nodev,noexec,nosuid proc /proc
-
 alias cryptsetup="cryptsetup --disable-locks"
+alias mount="mount -n"
 
-CRYPT_ROOT="$(sed -n 's/^.*crypt_root=\([^ $]*\).*$/\1/p' /proc/cmdline)"
-if [ -z "${CRYPT_ROOT}" ]; then
+#CRYPT_ROOT="$(sed -n 's/^.*crypt_root=\([^ $]*\).*$/\1/p' /proc/cmdline)"
+CRYPT_ROOT="$(cmdline crypt_root)"
+if [ "$?" -ne "0" ] || [ -z "${CRYPT_ROOT}" ]; then
     echo "crypt_root was not specified on the command line."
     echo -n "Contents of /proc/cmdline: "; cat /proc/cmdline
     exit 1
 fi
 
-if ! cryptsetup isLuks "${CRYPT_ROOT}"; then
-    echo "crypt_root was not identified as a LUKS device."
+for _ in $(seq 20); do
+    if findfs "${CRYPT_ROOT}" 2>&1 >/dev/null; then
+        break
+    fi
+
+    echo "Waiting for ${CRYPT_ROOT} to show up in /dev..."
+    sleep 1
+done
+
+CRYPT_ROOT_PATH="$(findfs ${CRYPT_ROOT})"
+if [ "$?" -ne "0" ] || [ -z "${CRYPT_ROOT_PATH}" ]; then
+    echo "${CRYPT_ROOT} does not exist."
     exit 1
 fi
 
-while ! cryptsetup luksOpen "${CRYPT_ROOT}" root; do
-    echo "Could not open ${CRYPT_ROOT}. Trying again..."
+if ! cryptsetup isLuks "${CRYPT_ROOT_PATH}"; then
+    echo "${CRYPT_ROOT_PATH} was not identified as a LUKS device."
+    exit 1
+fi
+
+while ! cryptsetup luksOpen "${CRYPT_ROOT_PATH}" root; do
+    echo "Could not open ${CRYPT_ROOT_PATH}. Trying again..."
 done
-echo "Opened ${CRYPT_ROOT} as /dev/mapper/root."
+echo "Opened ${CRYPT_ROOT_PATH} as /dev/mapper/root."
 
 if ! mount /dev/mapper/root /mnt; then
     echo "Could not mount /dev/mapper/root."
     exit 1
 fi
+
+umount /sys
+umount /proc
+#umount /dev
 
 echo "Switching to new root..."
 exec switch_root /mnt /sbin/init
@@ -129,17 +161,10 @@ EOF
     }
     trap cleanup RETURN
 
-    gen_init_cpio - > "${INITRAMFS_LOCATION}" <<EOF
-# devices
-dir /dev 0755 0 0
-nod /dev/console 660 0 0 c 5 1
-nod /dev/null 666 0 0 c 1 3
-nod /dev/zero 666 0 0 c 1 5
-nod /dev/tty0 600 0 0 c 4 0
-nod /dev/tty1 600 0 0 c 4 1
+    gen_init_cpio - > "$1" <<EOF
 # base layout
-#dir /.initrd
 dir /bin 0755 0 0
+dir /dev 0755 0 0
 dir /mnt 0755 0 0
 dir /proc 0555 0 0
 dir /sys 0555 0 0
@@ -152,9 +177,6 @@ file /init ${INIT_LOCATION} 0755 0 0
 EOF
 
     cpio -itvnF "${INITRAMFS_LOCATION}" 2>/dev/null
-
-    # TODO: support blkid naming
-    # BusyBox has a blkid applet
 }
 
 build_kernel() {
