reintegrify-root: add new script
Wow this was frustrating to write. What a hack

diff --git a/genkernel b/genkernel
--- a/genkernel
+++ b/genkernel
@@ -78,103 +78,86 @@ build_initramfs() {
 #!/bin/sh
 
 panic() {
-    printf "The kernel will panic as soon as you press Enter.\n"
-    read
+  printf "The kernel will panic as soon as you press Enter.\n"
+  read
 }
 trap panic EXIT
 
-mount -t devtmpfs none /dev
 mount -t proc none /proc
 mount -t sysfs none /sys
+mount -t devtmpfs none /dev
 
 set -euo pipefail
 
 exec >/dev/console </dev/console 2>&1
 
 cmdline() {
-    local value
-    value=" $(cat /proc/cmdline) "
-    value="${value##* ${1}=}"
-    value="${value%% *}"
-    [ "${value}" != "" ] && printf "%s\n" "${value}"
-}
-
-# https://gitlab.com/cryptsetup/cryptsetup/-/issues/504
-deintegrify() {
-    TABLE="$(dmsetup table "$1" --showkeys)"
-
-    # bail out if unknown algorithm
-    printf "%s" "${TABLE}" | grep -q "capi:authenc(hmac(sha256),.*)-plain64"
-
-    KEY_LENGTH_BYTES=64
-    OLD_KEY="$(printf "%s" "${TABLE}" | cut -f5 -d' ')"
-    NEW_KEY="$(printf "%s" "${OLD_KEY}" | head -c$(( KEY_LENGTH_BYTES * 2 )))"
-
-    #echo -n "old: "; dmsetup table "$1"
-
-    dmsetup remove "$1"
-    printf "%s\n" "${TABLE}" | sed \
-      -e "s/capi:authenc(hmac(sha256),\(.*\))\([^ ]*\) /capi:\1\2 /" \
-      -e "s/${OLD_KEY}/${NEW_KEY}/" \
-      -e "s/ integrity:[^ ]*//" | \
-      awk '{ $9--; print $0 }' | dmsetup create --readonly "$1"
-
-    #echo -n "new: "; dmsetup table "$1"
+  local value
+  value=" $(cat /proc/cmdline) "
+  value="${value##* ${1}=}"
+  value="${value%% *}"
+  [ "${value}" != "" ] && printf "%s\n" "${value}"
 }
 
 export PATH=/bin
 alias cryptsetup="cryptsetup --disable-locks"
 alias mount="mount -n"
 
-#CRYPT_ROOT="$(sed -n 's/^.*crypt_root=\([^ $]*\).*$/\1/p' /proc/cmdline)"
 CRYPT_ROOT="$(cmdline crypt_root)"
 if [ "$?" -ne "0" ] || [ -z "${CRYPT_ROOT}" ]; then
-    printf "crypt_root was not specified on the command line.\n"
-    printf "Contents of /proc/cmdline: "; cat /proc/cmdline
-    exit 1
+  printf "crypt_root was not specified on the command line.\n"
+  printf "Contents of /proc/cmdline: "; cat /proc/cmdline
+  exit 1
 fi
 
 for _ in $(seq 20); do
-    if findfs "${CRYPT_ROOT}" 2>&1 >/dev/null; then
-        break
-    fi
+  if findfs "${CRYPT_ROOT}" 2>&1 >/dev/null; then
+    break
+  fi
 
-    printf "Waiting for ${CRYPT_ROOT} to show up in /dev...\n"
-    sleep 1
+  printf "Waiting for ${CRYPT_ROOT} to show up in /dev...\n"
+  sleep 1
 done
 
 CRYPT_ROOT_PATH="$(findfs ${CRYPT_ROOT})"
 if [ "$?" -ne "0" ] || [ -z "${CRYPT_ROOT_PATH}" ]; then
-    printf "${CRYPT_ROOT} does not exist.\n"
-    exit 1
+  printf "${CRYPT_ROOT} does not exist.\n"
+  exit 1
 fi
 
 if ! cryptsetup isLuks "${CRYPT_ROOT_PATH}"; then
-    printf "${CRYPT_ROOT_PATH} was not identified as a LUKS device.\n"
-    exit 1
+  printf "${CRYPT_ROOT_PATH} was not identified as a LUKS device.\n"
+  exit 1
 fi
 
 while ! cryptsetup luksOpen "${CRYPT_ROOT_PATH}" root; do
-    printf "Could not open ${CRYPT_ROOT_PATH}. Trying again...\n"
+  printf "Could not open ${CRYPT_ROOT_PATH}. Trying again...\n"
 done
 printf "Opened ${CRYPT_ROOT_PATH} as /dev/mapper/root.\n"
 
-if ! mount /dev/mapper/root /mnt; then
-    if deintegrify root; then
-        printf "!!!!!!!!!!! AEAD integrity data failed to validate. Someone\n"
-        printf "! WARNING ! may have tampered with your disk, or shut down\n"
-        printf "!!!!!!!!!!! abruptly. Press Enter to boot in read-only mode.\n"
+if ! e2fsck -C0 /dev/mapper/root || ! mount /dev/mapper/root /mnt; then
+  if dmesg | grep -q 'INTEGRITY AEAD ERROR'; then
+    printf "!!!!!!!!!!! AEAD integrity data failed to validate. Someone may have tampered\n"
+    printf "! WARNING ! with your disk, or the system may have shut down abruptly.\n"
+    printf "!!!!!!!!!!! Trust current disk contents and recompute integrity checksums? [y/N]: "
+    if head -n1 | grep -Fixq -e y -e yes; then
+      deintegrify root
+      if ! e2fsck -C0 /dev/mapper/root; then
+        printf 'e2fsck failed; press Enter to continue'
         read
-
-        mount -o ro /dev/mapper/root /mnt
-    else
-        printf "Could not mount /dev/mapper/root.\n"
-        exit 1
+      fi
+      create-snapshot root
     fi
+  fi
 fi
 
-umount /sys
+if ! cut -d' ' -f1 /proc/mounts | grep -Fxq '/dev/mapper/root' && ! mount /dev/mapper/root /mnt; then
+  printf "Could not mount /dev/mapper/root.\n"
+  exit 1
+fi
+
 umount /proc
+umount /sys
 #umount /dev
 
 printf "Switching to new root...\n"
@@ -198,9 +181,16 @@ dir /mnt 0755 0 0
 dir /proc 0555 0 0
 dir /sys 0555 0 0
 dir /tmp 1777 0 0
-# busybox
+# reintegrify
+file /bin/create-snapshot /usr/local/bin/create-snapshot 0755 0 0
+file /bin/deintegrify /usr/local/bin/deintegrify 0755 0 0
+file /bin/e2fsck /sbin/e2fsck.static 0755 0 0
+# GNU dd needed for O_DIRECT
+file /bin/dd /bin/dd.static 0755 0 0
+# cryptsetup
 file /bin/cryptsetup /sbin/cryptsetup 0755 0 0
 file /bin/dmsetup /sbin/dmsetup.static 0755 0 0
+# busybox
 file /bin/busybox /bin/busybox 0755 0 0
 slink /bin/sh busybox 0777 0 0
 file /init ${INIT_LOCATION} 0755 0 0
